/*
 * Copyright 2024 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.test.ui.pages.section6

import uk.gov.hmrc.test.ui.pages.base.{BasePage, CommonPage}
import uk.gov.hmrc.test.ui.pages.base.CommonPage.{clearCacheForSection, fillSection1ForDeclaration, fillSection2ForDeclaration, fillSection3ForDeclaration, fillSection4ForDeclaration, fillSection5ForDeclaration}
import uk.gov.hmrc.test.ui.pages.section2.EntryIntoDeclarantRecordsPage
import uk.gov.hmrc.test.ui.pages.section3.DestinationCountryPage
import uk.gov.hmrc.test.ui.pages.section5.{AdditionalProcedureCodesPage, ProcedureCodesPage}
import uk.gov.hmrc.test.ui.pages.section6.DetailKeys.Section6

object SummarySection6Page extends BasePage {

  def backButtonHref: String = ContainerListPage.path

  val path: String           = "/declaration/summary-section/6"
  val title: String          = "Check your answers"

  override def checkExpanders(): Unit = ()

  // ex: fillPage()

  override def fillPage(values: String*): Unit = {
    waitForCssSelector(".govuk-summary-card__title")
    checkSectionSummary(Section6)
  }

  def fillAllForSections6(decType: String, AdditionalDecType: String): Unit = {
    fillSection1ForDeclaration(decType, AdditionalDecType)
    fillSection2ForDeclaration()
    fillSection3ForDeclaration()
    fillSection4ForDeclaration()
    fillSection5ForDeclaration()
  }

  def section6ClearanceJourney1():Unit= {
    TransportLeavingTheBorderPage.checkPage()
    TransportLeavingTheBorderPage.fillPage("Sea transport")
    CommonPage.continue()
    WarehousePage.checkPage()
    WarehousePage.fillPage("Yes", "R1234567GB")
    CommonPage.continue()
    SupervisingCustomsOfficePage.checkPage()
    SupervisingCustomsOfficePage.fillPage("GBBTH001")
    CommonPage.continue()
    DepartureTransportPage.checkPage()
    DepartureTransportPage.fillPage("Ship IMO number")
    CommonPage.continue()
    ExpressConsignmentPage.checkPage()
    ExpressConsignmentPage.fillPage("Yes")
    CommonPage.continue()
    TransportPaymentPage.checkPage()
    TransportPaymentPage.fillPage("Payment in cash")
    CommonPage.continue()
    ContainerPage.checkPage()
    ContainerPage.fillPage("Yes", "Container1")
    CommonPage.continue()
    SealYesNoPage.checkPage()
    SealYesNoPage.fillPage("Yes")
    CommonPage.continue()
    SealPage.checkPage()
    SealPage.fillPage("Seal1")
    CommonPage.continue()
    SealListPage.checkPage()
    SealListPage.fillPage("No")
    CommonPage.continue()
    ContainerListPage.checkPage()
    ContainerListPage.fillPage("No")
    CommonPage.continue()
  }

  def section6ClearanceJourney2():Unit={
    EntryIntoDeclarantRecordsPage.navigateToPage(EntryIntoDeclarantRecordsPage.path)
    EntryIntoDeclarantRecordsPage.fillPage("No")
    CommonPage.continue()
    ProcedureCodesPage.navigateToItemPage(ProcedureCodesPage.pageId)
    ProcedureCodesPage.fillPage("0017")
    CommonPage.continue()
    AdditionalProcedureCodesPage.checkPage()
    AdditionalProcedureCodesPage.fillPage("16M")
    CommonPage.continue()
    TransportLeavingTheBorderPage.navigateToPage(TransportLeavingTheBorderPage.path)
    TransportLeavingTheBorderPage.checkPage()
    TransportLeavingTheBorderPage.fillPage("Fixed transport installations")
    logger.info("Due to the fix transport installation we need to clear Departure transport")
    clearCacheForSection(6)
    CommonPage.continue()
    WarehousePage.checkPage()
    WarehousePage.fillPage("Yes", "R1234567GB")
    CommonPage.continue()
    SupervisingCustomsOfficePage.checkPage()
    SupervisingCustomsOfficePage.fillPage("GBBTH001")
    CommonPage.continue()
    ExpressConsignmentPage.checkPage()
    ExpressConsignmentPage.fillPage("Yes")
    CommonPage.continue()
    TransportPaymentPage.checkPage()
    TransportPaymentPage.fillPage("Payment in cash")
    CommonPage.continue()
  }

  def section6ClearanceArrivedJourney(): Unit = {
    ProcedureCodesPage.navigateToItemPage(ProcedureCodesPage.pageId)
    ProcedureCodesPage.checkPage()
    ProcedureCodesPage.fillPage("1007")
    CommonPage.continue()
    AdditionalProcedureCodesPage.checkPage()
    AdditionalProcedureCodesPage.fillPage("1CS")
    CommonPage.continue()
    TransportLeavingTheBorderPage.navigateToPage(TransportLeavingTheBorderPage.path)
    TransportLeavingTheBorderPage.checkPage()
    TransportLeavingTheBorderPage.fillPage("Roll on Roll off (RoRo)")
    CommonPage.continue()
    WarehousePage.checkPage()
    WarehousePage.fillPage("Yes", "R1234567GB")
    CommonPage.continue()
    SupervisingCustomsOfficePage.checkPage()
    SupervisingCustomsOfficePage.fillPage("GBBTH001")
    CommonPage.continue()
    DepartureTransportPage.checkPage()
    DepartureTransportPage.fillPage("Ship IMO number")
    CommonPage.continue()
    ExpressConsignmentPage.checkPage()
    ExpressConsignmentPage.fillPage("No")
    CommonPage.continue()
    ContainerPage.checkPage()
    ContainerPage.fillPage("No")
    CommonPage.continue()
  }
  def section6OccasionalJourney1():Unit={
    TransportLeavingTheBorderPage.checkPage()
    TransportLeavingTheBorderPage.fillPage("Sea transport")
    CommonPage.continue()
    SupervisingCustomsOfficePage.checkPage()
    SupervisingCustomsOfficePage.fillPage("GBBTH001")
    CommonPage.continue()
    InlandOrBorderPage.checkPage()
    InlandOrBorderPage.fillPage("Customs controlled location")
    CommonPage.continue()
    InlandModeOfTransportPage.checkPage()
    InlandModeOfTransportPage.fillPage("Air transport")
    CommonPage.continue()
    BorderTransportPage.checkPage()
    BorderTransportPage.fillPage("Ship IMO number")
    CommonPage.continue()
    TransportCountryPage.checkPage()
    TransportCountryPage.fillPage("Macao")
    CommonPage.continue()
    ExpressConsignmentPage.checkPage()
    ExpressConsignmentPage.fillPage("Yes")
    CommonPage.continue()
    TransportPaymentPage.checkPage()
    TransportPaymentPage.fillPage("Payment in cash")
    CommonPage.continue()
    ContainerPage.checkPage()
    ContainerPage.fillPage("Yes", "Container1")
    CommonPage.continue()
    SealYesNoPage.checkPage()
    SealYesNoPage.fillPage("Yes")
    CommonPage.continue()
    SealPage.checkPage()
    SealPage.fillPage("Seal1")
    CommonPage.continue()
    SealListPage.checkPage()
    SealListPage.fillPage("No")
    CommonPage.continue()
    ContainerListPage.checkPage()
    ContainerListPage.fillPage("No")
    CommonPage.continue()
  }
  def section6OccasionalJourney2():Unit={
    clearCacheForSection(6)
    DestinationCountryPage.navigateToPage(DestinationCountryPage.path)
    DestinationCountryPage.checkPage()
    DestinationCountryPage.fillPage("Jersey")
    CommonPage.continue()
    TransportLeavingTheBorderPage.navigateToPage(TransportLeavingTheBorderPage.path)
    TransportLeavingTheBorderPage.checkPage()
    TransportLeavingTheBorderPage.fillPage("Rail transport")
    CommonPage.continue()
    SupervisingCustomsOfficePage.checkPage()
    SupervisingCustomsOfficePage.fillPage("GBBTH001")
    CommonPage.continue()
    InlandOrBorderPage.checkPage()
    InlandOrBorderPage.fillPage("Border location")
    CommonPage.continue()
    TransportCountryPage.checkPage()
    TransportCountryPage.fillPage("Iraq")
    CommonPage.continue()
    ExpressConsignmentPage.checkPage()
    ExpressConsignmentPage.fillPage("No")
    CommonPage.continue()
    ContainerListPage.selectContainerToRemove(0)
    ContainerRemovePage.checkPage()
    ContainerRemovePage.fillPage("Yes", "Container1")
    CommonPage.continue()
    ContainerPage.checkPage()
    ContainerPage.fillPage("No")
    CommonPage.continue()
  }

  def section6CommonJourney1():Unit= {
    TransportLeavingTheBorderPage.checkPage()
    TransportLeavingTheBorderPage.fillPage("Sea transport")
    CommonPage.continue()
    SupervisingCustomsOfficePage.checkPage()
    SupervisingCustomsOfficePage.fillPage("GBBTH001")
    CommonPage.continue()
    InlandOrBorderPage.checkPage()
    InlandOrBorderPage.fillPage("Customs controlled location")
    CommonPage.continue()
    InlandModeOfTransportPage.checkPage()
    InlandModeOfTransportPage.fillPage("Sea transport")
    CommonPage.continue()
  }
  def section6SimplifiedJourney1Cont():Unit={
    BorderTransportPage.checkPage()
    BorderTransportPage.fillPage("Flight number")
    CommonPage.continue()
    TransportCountryPage.checkPage()
    TransportCountryPage.fillPage("Macao")
    CommonPage.continue()
    ExpressConsignmentPage.checkPage()
    ExpressConsignmentPage.fillPage("Yes")
    CommonPage.continue()
    TransportPaymentPage.checkPage()
    TransportPaymentPage.fillPage("Payment in cash")
    CommonPage.continue()
    ContainerPage.checkPage()
    ContainerPage.fillPage("Yes", "Container1")
    CommonPage.continue()
    SealYesNoPage.checkPage()
    SealYesNoPage.fillPage("Yes")
    CommonPage.continue()
    SealPage.checkPage()
    SealPage.fillPage("Seal1")
    CommonPage.continue()
    SealListPage.checkPage()
    SealListPage.fillPage("No")
    CommonPage.continue()
    ContainerListPage.checkPage()
    ContainerListPage.fillPage("Yes")
    CommonPage.continue()
    ContainerPage.fillPage("Container2")
    CommonPage.continue()
    SealYesNoPage.checkPage()
    SealYesNoPage.fillPage("No")
    CommonPage.continue()
    ContainerListPage.checkPage()
    ContainerListPage.fillPage("No")
    CommonPage.continue()
  }
  
  def section6StandardJourney1():Unit={
    DepartureTransportPage.checkPage()
    DepartureTransportPage.fillPage("Ship IMO number")
    CommonPage.continue()
    BorderTransportPage.checkPage()
    BorderTransportPage.fillPage("Vehicle registration")
    CommonPage.continue()
    TransportCountryPage.checkPage()
    TransportCountryPage.fillPage("Macao")
    CommonPage.continue()
    ExpressConsignmentPage.checkPage()
    ExpressConsignmentPage.fillPage("Yes")
    CommonPage.continue()
    TransportPaymentPage.checkPage()
    TransportPaymentPage.fillPage("Payment in cash")
    CommonPage.continue()
    ContainerPage.checkPage()
    ContainerPage.fillPage("Yes", "Container1")
    CommonPage.continue()
    SealYesNoPage.checkPage()
    SealYesNoPage.fillPage("Yes")
    CommonPage.continue()
    SealPage.checkPage()
    SealPage.fillPage("Seal1")
    CommonPage.continue()
  }
  
   def section6SupplementaryJourney1():Unit={
     TransportLeavingTheBorderPage.checkPage()
     TransportLeavingTheBorderPage.fillPage("Sea transport")
     CommonPage.continue()
     SupervisingCustomsOfficePage.checkPage()
     SupervisingCustomsOfficePage.fillPage("GBBTH001")
     CommonPage.continue()
     InlandModeOfTransportPage.checkPage()
     InlandModeOfTransportPage.fillPage("Sea transport")
     CommonPage.continue()
     DepartureTransportPage.checkPage()
     DepartureTransportPage.fillPage("Ship IMO number")
     CommonPage.continue()
     BorderTransportPage.checkPage()
     BorderTransportPage.fillPage("Vehicle registration")
     CommonPage.continue()
     TransportCountryPage.checkPage()
     TransportCountryPage.fillPage("Macao")
     CommonPage.continue()
     ContainerPage.checkPage()
     ContainerPage.fillPage("Yes", "Container1")
     CommonPage.continue()
     SealYesNoPage.checkPage()
     SealYesNoPage.fillPage("Yes")
     CommonPage.continue()
     SealPage.checkPage()
     SealPage.fillPage("Seal1")
     CommonPage.continue()
     SealListPage.checkPage()
     SealListPage.fillPage("No")
     CommonPage.continue()
     ContainerListPage.checkPage()
     ContainerListPage.fillPage("No")
     CommonPage.continue()
  }
}
