/*
 * Copyright 2023 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.test.ui.pages.section5

import org.openqa.selenium.WebElement
import uk.gov.hmrc.test.ui.cucumber.stepdefs.CommonStepDef.genSequenceId
import uk.gov.hmrc.test.ui.pages.base.{BasePage, CommonPage}
import uk.gov.hmrc.test.ui.pages.base.CommonPage.{fillSection2ForDeclaration, fillSection3ForDeclaration, fillSection4ForDeclaration}
import uk.gov.hmrc.test.ui.pages.section2.{AuthorisationPage, AuthorisationRemovePage, AuthorisationsListPage, AuthorisationsYesNoPage}
import uk.gov.hmrc.test.ui.pages.section4.NatureOfTransactionPage
import uk.gov.hmrc.test.ui.pages.section5.DetailsKeys.Section5

object SummarySection5Page extends BasePage {

  def backButtonHref: String = DeclarationItemsListPage.path
  val path: String           = "/declaration/summary-section/5"
  val title: String          = "Check your answers"

  override def checkExpanders(): Unit = ()

  // ex: fillPage()

  override def fillPage(values: String*): Unit = checkSectionSummary(Section5)

  def removeItem(): Unit = clickByCssSelector(".item-1-heading a")

  def addItemWarning(): WebElement = findElementByClassName("govuk-warning-text__text")

  def addItem(): Unit = clickById("add-item")

  def section5Journey1():Unit={
    fillSection2ForDeclaration()
    fillSection3ForDeclaration()
    fillSection4ForDeclaration()
    AddDeclarationItemPage.checkPage()
    AddDeclarationItemPage.fillPage()
    ProcedureCodesPage.checkPage()
  }

  def section5Journey2():Unit={
    fillSection2ForDeclaration()
    fillSection3ForDeclaration()
    fillSection4ForDeclaration()
    AuthorisationsListPage.navigateToPage(AuthorisationsListPage.path)
    AuthorisationsListPage.removeAuthCode(0)
    AuthorisationRemovePage.checkPage()
    AuthorisationRemovePage.fillPage("Yes", "0")
    CommonPage.continue()
    AuthorisationPage.checkPage()
    AuthorisationPage.fillPage(genSequenceId("first"), "EXRR", "GB123456789006")
    CommonPage.continue()
    AddDeclarationItemPage.navigateToPage(AddDeclarationItemPage.path)
    AddDeclarationItemPage.fillPage()
    ProcedureCodesPage.checkPage()
    ProcedureCodesPage.fillPage("1040")
    CommonPage.continue()
    AdditionalProcedureCodesPage.checkPage()
    AdditionalProcedureCodesPage.fillPage("000")
    CommonPage.continue()
  }

  def section5ProcedureCodesPageToCommodityDetailsPage():Unit={
    ProcedureCodesPage.fillPage("1042")
    CommonPage.continue()
    AdditionalProcedureCodesPage.checkPage()
    AdditionalProcedureCodesPage.fillPage("F75 and 2ES and 1CD")
    CommonPage.continue()
    FiscalReferencesYesNoPage.checkPage()
    FiscalReferencesYesNoPage.fillPage("Yes")
    CommonPage.continue()
    FiscalReferencesPage.checkPage()
    FiscalReferencesPage.fillPage("Andorra", "AD", "1234")
    CommonPage.continue()
    FiscalReferencesListPage.checkPage()
    FiscalReferencesListPage.fillPage("No")
    CommonPage.continue()
    CommodityDetailsPage.checkPage()
  }
  def section5section5ProcedureCodesPageToDeclarationItemsListPage():Unit={
    ProcedureCodesPage.fillPage("1040")
    CommonPage.continue()
    AdditionalProcedureCodesPage.checkPage()
    AdditionalProcedureCodesPage.fillPage("000")
    CommonPage.continue()
    CommodityDetailsPage.checkPage()
    CommodityDetailsPage.fillPage("90034003", "St Andrews golf ball whisky")
    CommonPage.continue()
    DangerousGoodsCodePage.navigateToItemPage(DangerousGoodsCodePage.pageId)
    DangerousGoodsCodePage.fillPage("Yes", "1234")
    CommonPage.continue()
    NationalAdditionalCodesPage.checkPage()
    NationalAdditionalCodesPage.fillPage("Yes", "A123")
    CommonPage.continue()
    NationalAdditionalCodesListPage.checkPage()
    NationalAdditionalCodesListPage.fillPage("No")
    CommonPage.continue()
    StatisticalValuePage.checkPage()
    StatisticalValuePage.fillPage("1000")
    CommonPage.continue()
    PackageInformationPage.checkPage()
    PackageInformationPage.fillPage(genSequenceId("first"), "Aerosol", "20", "1234")
    CommonPage.continue()
    PackageInformationListPage.checkPage()
    PackageInformationListPage.fillPage("No")
    CommonPage.continue()
    CommodityMeasurePage.checkPage()
    CommodityMeasurePage.fillPage("500", "700")
    CommonPage.continue()
    SupplementaryUnitsPage.checkPage()
    SupplementaryUnitsPage.fillPage("Yes", "12")
    CommonPage.continue()
    AdditionalInformationYesNoPage.checkPage()
    AdditionalInformationYesNoPage.fillPage("Yes")
    CommonPage.continue()
    AdditionalInformationPage.checkPage()
    AdditionalInformationPage.fillPage(genSequenceId("first"), "00400", "EXPORTER")
    CommonPage.continue()
    AdditionalInformationListPage.checkPage()
    AdditionalInformationListPage.fillPage("No")
    CommonPage.continue()
    LicenseRequiredYesNoPage.checkPage()
    LicenseRequiredYesNoPage.fillPage("No")
    CommonPage.continue()
    AdditionalDocumentPage.checkPage()
    AdditionalDocumentPage.fillPage(genSequenceId("first"), "C501", "GBAEOC71757")
    CommonPage.continue()
    AdditionalDocumentListPage.checkPage()
    AdditionalDocumentListPage.fillPage("No")
    CommonPage.continue()
    DeclarationItemsListPage.checkPage()
    //click change link and update existing item details//
    DeclarationItemsListPage.changeItem()
    ProcedureCodesPage.checkPage()
    ProcedureCodesPage.fillPage("1044")
    CommonPage.continue()
    AdditionalProcedureCodesPage.checkPage()
    AdditionalProcedureCodesPage.fillPage("1SW")
    CommonPage.continue()
    CommodityDetailsPage.checkPage()
    CommodityDetailsPage.fillPage("95034005", "Straw for bottles")
    CommonPage.continue()
    DangerousGoodsCodePage.navigateToItemPage(DangerousGoodsCodePage.pageId)
    DangerousGoodsCodePage.fillPage("Yes", "1034")
    CommonPage.continue()
    NationalAdditionalCodesListPage.checkPage()
    NationalAdditionalCodesListPage.fillPage("No")
    CommonPage.continue()
    StatisticalValuePage.checkPage()
    StatisticalValuePage.fillPage("1099")
    CommonPage.continue()
    //clicking change Package-Information-List page  and update package information//
    PackageInformationListPage.checkPage()
    PackageInformationListPage.changePackageInformation(0)
    PackageInformationPage.fillPage(genSequenceId("first"), "Basket", "11", "456")
    CommonPage.continue()
    PackageInformationListPage.fillPage("No")
    CommonPage.continue()
    CommodityMeasurePage.checkPage()
    CommodityMeasurePage.fillPage("580", "706")
    CommonPage.continue()
    SupplementaryUnitsPage.checkPage()
    SupplementaryUnitsPage.fillPage("Yes", "62")
    CommonPage.continue()
    //clicking change Additional-Information-List page  and update Additional information//
    AdditionalInformationListPage.checkPage()
    AdditionalInformationListPage.changeAdditionalInformation(0)
    AdditionalInformationPage.fillPage(genSequenceId("first"), "00408", "DATAREADER")
    CommonPage.continue()
    AdditionalInformationListPage.fillPage("No")
    CommonPage.continue()
    LicenseRequiredYesNoPage.checkPage()
    LicenseRequiredYesNoPage.fillPage("Yes")
    CommonPage.continue()
    AdditionalDocumentListPage.checkPage()
    //clicking change Additional-Documentation-List page  and update Additional Documents//
    AdditionalDocumentListPage.changeAdditionalDocuments(0)
    AdditionalDocumentPage.fillPage(genSequenceId("first"), "9104", "GBAEOC717992")
    CommonPage.continue()
    AdditionalDocumentListPage.checkPage()
    AdditionalDocumentListPage.fillPage("No")
    CommonPage.continue()
    DeclarationItemsListPage.checkPage()
    DeclarationItemsListPage.fillPage("No")
    CommonPage.continue()
  }
  
  def section5Journey3():Unit={
    fillSection2ForDeclaration()
    fillSection3ForDeclaration()
    fillSection4ForDeclaration()
    AuthorisationsListPage.navigateToPage(AuthorisationsListPage.path)
    AuthorisationsListPage.removeAuthCode(0)
    AuthorisationRemovePage.checkPage()
    AuthorisationRemovePage.fillPage("Yes", "0")
    CommonPage.continue()
    AuthorisationsYesNoPage.fillPage("Yes")
    CommonPage.continue()
    AuthorisationPage.checkPage()
    AuthorisationPage.fillPage(genSequenceId("first"), "EXRR", "GB123456789006")
    CommonPage.continue()
    AddDeclarationItemPage.navigateToPage(AddDeclarationItemPage.path)
    AddDeclarationItemPage.fillPage()
    ProcedureCodesPage.checkPage()
    ProcedureCodesPage.fillPage("1042")
    CommonPage.continue()
    AdditionalProcedureCodesPage.checkPage()
    AdditionalProcedureCodesPage.fillPage("F75")
    CommonPage.continue()
    FiscalReferencesYesNoPage.checkPage()
    FiscalReferencesYesNoPage.fillPage("No")
    CommonPage.continue()
    CommodityDetailsPage.checkPage()
    CommodityDetailsPage.fillPage("28034000", "Old St Andrews golf ball whisky")
    CommonPage.continue()
    DangerousGoodsCodePage.checkPage()
    DangerousGoodsCodePage.fillPage("No")
    CommonPage.continue()
    CusCodePage.checkPage()
    CusCodePage.fillPage("No")
    CommonPage.continue()
    VatRatingPage.checkPage()
    VatRatingPage.fillPage("Report VAT rating after this declaration has been submitted")
    CommonPage.continue()
    NationalAdditionalCodesPage.checkPage()
    NationalAdditionalCodesPage.fillPage("No")
    CommonPage.continue()
    StatisticalValuePage.checkPage()
    StatisticalValuePage.fillPage("2000")
    CommonPage.continue()
    PackageInformationPage.checkPage()
    PackageInformationPage.fillPage(genSequenceId("first"), "Barrel", "119", "1204")
    CommonPage.continue()
    PackageInformationListPage.checkPage()
    PackageInformationListPage.fillPage("No")
    CommonPage.continue()
    CommodityMeasurePage.checkPage()
    CommodityMeasurePage.fillPage("400", "800")
    CommonPage.continue()
    SupplementaryUnitsPage.checkPage()
    SupplementaryUnitsPage.fillPage("No")
    CommonPage.continue()
    AdditionalInformationYesNoPage.checkPage()
    AdditionalInformationYesNoPage.fillPage("No")
    CommonPage.continue()
    LicenseRequiredYesNoPage.checkPage()
    LicenseRequiredYesNoPage.fillPage("No")
    CommonPage.continue()
    AdditionalDocumentsYesNoPage.checkPage()
    AdditionalDocumentsYesNoPage.fillPage("No")
    CommonPage.continue()
    DeclarationItemsListPage.checkPage()
    DeclarationItemsListPage.fillPage("No")
    CommonPage.continue()
  }
  def section5SkippedVATRatingPage():Unit={
    NationalAdditionalCodesPage.checkPage()
    NationalAdditionalCodesPage.fillPage("Yes", "A123")
    CommonPage.continue()
    NationalAdditionalCodesListPage.checkPage()
    NationalAdditionalCodesListPage.fillPage("No")
    CommonPage.continue()
    StatisticalValuePage.checkPage()
    StatisticalValuePage.fillPage("1080")
    CommonPage.continue()
    PackageInformationPage.checkPage()
    PackageInformationPage.fillPage(genSequenceId("first"), "Aerosol", "20", "1234")
    CommonPage.continue()
    PackageInformationListPage.checkPage()
    PackageInformationListPage.fillPage("No")
    CommonPage.continue()
    CommodityMeasurePage.checkPage()
    CommodityMeasurePage.fillPage("500", "710")
    CommonPage.continue()
    SupplementaryUnitsPage.checkPage()
    SupplementaryUnitsPage.fillPage("Yes", "30")
    CommonPage.continue()
    AdditionalInformationYesNoPage.checkPage()
    AdditionalInformationYesNoPage.fillPage("Yes")
    CommonPage.continue()
    AdditionalInformationPage.checkPage()
    AdditionalInformationPage.fillPage(genSequenceId("first"), "00400", "EXPORTER")
    CommonPage.continue()
    AdditionalInformationListPage.checkPage()
    AdditionalInformationListPage.fillPage("No")
    CommonPage.continue()
    LicenseRequiredYesNoPage.checkPage()
    LicenseRequiredYesNoPage.fillPage("Yes")
    CommonPage.continue()
  }
  
  def skipDocumentsRequiresYesNoPage():Unit={
    AdditionalDocumentPage.checkPage()
    AdditionalDocumentPage.fillPage(genSequenceId("first"), "C501", "GBAEOC71757")
    CommonPage.continue()
    AdditionalDocumentListPage.checkPage()
    AdditionalDocumentListPage.fillPage("No")
    CommonPage.continue()
    DeclarationItemsListPage.checkPage()
    DeclarationItemsListPage.fillPage("Yes")
    CommonPage.continue()
    //Adding Second item//
    ProcedureCodesPage.checkPage()
    ProcedureCodesPage.fillPage("1040")
    CommonPage.continue()
    AdditionalProcedureCodesPage.checkPage()
    AdditionalProcedureCodesPage.fillPage("000")
    CommonPage.continue()
    CommodityDetailsPage.checkPage()
    CommodityDetailsPage.fillPage("28034008", "Old St Andrews golf ball whisky")
    CommonPage.continue()
    DangerousGoodsCodePage.checkPage()
    DangerousGoodsCodePage.fillPage("No")
    CommonPage.continue()
    CusCodePage.checkPage()
    CusCodePage.fillPage("No")
    CommonPage.continue()
    NationalAdditionalCodesPage.checkPage()
    NationalAdditionalCodesPage.fillPage("No")
    CommonPage.continue()
    StatisticalValuePage.checkPage()
    StatisticalValuePage.fillPage("2000")
    CommonPage.continue()
    PackageInformationPage.checkPage()
    PackageInformationPage.fillPage(genSequenceId("first"), "Barrel", "119", "1204")
    CommonPage.continue()
    PackageInformationListPage.checkPage()
    PackageInformationListPage.fillPage("No")
    CommonPage.continue()
    CommodityMeasurePage.checkPage()
    CommodityMeasurePage.fillPage("400", "800")
    CommonPage.continue()
    SupplementaryUnitsPage.checkPage()
    SupplementaryUnitsPage.fillPage("No")
    CommonPage.continue()
    AdditionalInformationYesNoPage.checkPage()
    AdditionalInformationYesNoPage.fillPage("No")
    CommonPage.continue()
    LicenseRequiredYesNoPage.checkPage()
    LicenseRequiredYesNoPage.fillPage("No")
    CommonPage.continue()
    AdditionalDocumentPage.checkPage()
    AdditionalDocumentPage.fillPage(genSequenceId("first"), "C401", "GBXEOC71757")
    CommonPage.continue()
    AdditionalDocumentListPage.checkPage()
    AdditionalDocumentListPage.fillPage("No")
    CommonPage.continue()
    DeclarationItemsListPage.checkPage()
    DeclarationItemsListPage.fillPage("No")
    CommonPage.continue()
  }
  
  def  section5NatureOfTransactionPageToDeclarationItemsListPage():Unit={
    NatureOfTransactionPage.navigateToPage(NatureOfTransactionPage.path)
    NatureOfTransactionPage.fillPage("House removal")
    CommonPage.continue()
    DangerousGoodsCodePage.navigateToItemPage(DangerousGoodsCodePage.pageId)
    DangerousGoodsCodePage.fillPage("Yes", "1234")
    CommonPage.continue()
    NationalAdditionalCodesPage.checkPage()
    NationalAdditionalCodesPage.fillPage("Yes", "A123")
    CommonPage.continue()
    NationalAdditionalCodesListPage.checkPage()
    NationalAdditionalCodesListPage.fillPage("No")
    CommonPage.continue()
    StatisticalValuePage.checkPage()
    StatisticalValuePage.fillPage("1000")
    CommonPage.continue()
    PackageInformationPage.checkPage()
    PackageInformationPage.fillPage(genSequenceId("first"), "Aerosol", "5", "67")
    CommonPage.continue()
    PackageInformationListPage.checkPage()
    PackageInformationListPage.fillPage("No")
    CommonPage.continue()
    CommodityMeasurePage.checkPage()
    CommodityMeasurePage.fillPage("500", "700")
    CommonPage.continue()
    SupplementaryUnitsPage.checkPage()
    SupplementaryUnitsPage.fillPage("Yes", "12")
    CommonPage.continue()
    AdditionalInformationYesNoPage.checkPage()
    AdditionalInformationYesNoPage.fillPage("No")
    CommonPage.continue()
    LicenseRequiredYesNoPage.checkPage()
    LicenseRequiredYesNoPage.fillPage("No")
    CommonPage.continue()
    AdditionalDocumentPage.checkPage()
    AdditionalDocumentPage.fillPage(genSequenceId("first"), "C501", "GBAEOC71757")
    CommonPage.continue()
    AdditionalDocumentListPage.checkPage()
    AdditionalDocumentListPage.fillPage("No")
    CommonPage.continue()
    DeclarationItemsListPage.checkPage()
    DeclarationItemsListPage.fillPage("No")
    CommonPage.continue()
  }
}
