package uk.gov.hmrc.test.ui.specs.Section5

import org.scalatest.{BeforeAndAfterAll, BeforeAndAfterEach, GivenWhenThen}
import org.scalatest.featurespec.AnyFeatureSpec
import org.scalatest.prop.TableDrivenPropertyChecks
import org.scalatest.verbs.ShouldVerb
import uk.gov.hmrc.selenium.webdriver.{Browser, ScreenshotOnFailure}
import uk.gov.hmrc.test.ui.pages.base.CommonPage
import uk.gov.hmrc.test.ui.pages.base.CommonPage.CommonStepPage.genSequenceId
import uk.gov.hmrc.test.ui.pages.base.CommonPage.{background, fillSection1ForDeclaration}
import uk.gov.hmrc.test.ui.pages.section2.{EntryIntoDeclarantRecordsPage, IsThisExsPage}
import uk.gov.hmrc.test.ui.pages.section5.*
import uk.gov.hmrc.test.ui.pages.section5.SummarySection5Page.section5Journey1
import uk.gov.hmrc.test.ui.specs.BaseSpec

class ClearanceJourneySpec
    extends AnyFeatureSpec with BaseSpec with GivenWhenThen with ShouldVerb with BeforeAndAfterAll
    with BeforeAndAfterEach with Browser with TableDrivenPropertyChecks with ScreenshotOnFailure {
  Feature("Clearance Journey Section 5") {
    Scenario("Complete Items section on Clearance PreLodged declaration journey") {
      Given("the user clears data in cache")
      background()
      When("User fills Section1 for CLEARANCE, prelodged declaration")
      fillSection1ForDeclaration("CLEARANCE", "prelodged")
      And("User fills section2/3/4 and continues their journey to Procedure-codes page")
      section5Journey1()
      And("User selects 1100 as procedure code and continues")
      ProcedureCodesPage.fillPage("1100")
      CommonPage.continue()
      And("User lands on Additional-Procedure-Codes page")
      AdditionalProcedureCodesPage.checkPage()
      And("User selects F44 as additional procedure code and continues")
      AdditionalProcedureCodesPage.fillPage("F44")
      CommonPage.continue()
      And("User lands on Commodity-Details page")
      CommodityDetailsPage.checkPage()
      And("User enters only description as Old St Andrews golf ball whisky on commodity details page and continues")
      CommodityDetailsPage.fillPage("Old St Andrews golf ball whisky")
      CommonPage.continue()
      //Skipping dangerous code page when isEXS is No//
      And("User lands on Package-Information page")
      PackageInformationPage.checkPage()
      And("User enters Cylinder as package type, with 5 packages and 67 as shipping mark for first package info and continues")
      PackageInformationPage.fillPage(genSequenceId("first"), "Cylinder", "5", "67")
      CommonPage.continue()
      And("User lands on Package-Information-List page")
      PackageInformationListPage.checkPage()
      And("User selects No on package information list page and continues")
      PackageInformationListPage.fillPage("No")
      CommonPage.continue()
      And("User lands on Commodity-Measure page")
      CommodityMeasurePage.checkPage()
      And("User enters gross weight as 5090 and net weight as 7010 and continues")
      CommodityMeasurePage.fillPage("5090", "7010")
      CommonPage.continue()
      And("User lands on Additional-Information-YesNo page")
      AdditionalInformationYesNoPage.checkPage()
      And("User selects Yes to add additional information")
      AdditionalInformationYesNoPage.fillPage("Yes")
      CommonPage.continue()
      And("User lands on Additional-Information page")
      AdditionalInformationPage.checkPage()
      And("User enters 00409 as code and TESTER as required information as first additional information and continues")
      AdditionalInformationPage.fillPage(genSequenceId("first"), "00409", "TESTER")
      CommonPage.continue()
      And("User lands on Additional-Information-List page")
      AdditionalInformationListPage.checkPage()
      And("User selects No on additional information list page and continues")
      AdditionalInformationListPage.fillPage("No")
      CommonPage.continue()
      And("User lands on Additional-Document page")
      AdditionalDocumentPage.checkPage()
      And("User enters C676 as code and GBAEOC70057 as identifier for first additional document and continues")
      AdditionalDocumentPage.fillPage(genSequenceId("first"), "C676", "GBAEOC70057")
      CommonPage.continue()
      And("User lands on Additional-Document-List page")
      AdditionalDocumentListPage.checkPage()
      And("User selects No on additional document list page and continues")
      AdditionalDocumentListPage.fillPage("No")
      CommonPage.continue()
      And("User lands on Declaration-Items-List page")
      DeclarationItemsListPage.checkPage()
      And("User selects No on declaration items list page and continues")
      DeclarationItemsListPage.fillPage("No")
      CommonPage.continue()
      Then("User should land on MiniCYA-Section-5 page")
      SummarySection5Page.checkPage()
      And("User checks the MiniCYA page for Section-5")
      SummarySection5Page.fillPage()
      //check Fiscal Reference pages when Procedure code is 1042//
      When("User navigates to Procedure codes page")
      ProcedureCodesPage.navigateToItemPage(ProcedureCodesPage.pageId)
      And("User selects 1042 as procedure code and continues")
      ProcedureCodesPage.fillPage("1042")
      CommonPage.continue()
      And("User lands on Additional-Procedure-Codes page")
      AdditionalProcedureCodesPage.checkPage()
      And("User selects F75 as additional procedure code")
      AdditionalProcedureCodesPage.fillPage("F75")
      CommonPage.continue()
    //changing isThisEXS Yes and validating dangerous codes page//
      And("User navigates to Is This EXS page")
      IsThisExsPage.navigateToPage(IsThisExsPage.path)
      And("User selects Yes to is this exs and continues")
      IsThisExsPage.fillPage("Yes")
      CommonPage.continue()
      And("User navigates to Commodity-Details page and continues")
      CommodityDetailsPage.navigateToItemPage(CommodityDetailsPage.pageId)
      CommonPage.continue()
      And("User lands on Dangerous-Goods-Code page")
      DangerousGoodsCodePage.checkPage()
      And("User selects Yes to enter the code 1204 as dangerous goods and continues")
      DangerousGoodsCodePage.fillPage("Yes", "1204")
      CommonPage.continue()
      Then("User should navigate to MiniCYA-Section-5 page")
      SummarySection5Page.navigateToPage(SummarySection5Page.path)
      And("User checks the MiniCYA page for Section-5")
      SummarySection5Page.fillPage()
    }
    Scenario("Complete Items section on Clearance Arrived declaration journey") {
      Given("the user clears data in cache")
      background()
      When("User fills Section1 for CLEARANCE, arrived declaration")
      fillSection1ForDeclaration("CLEARANCE", "arrived")
      And("User fills section2/3/4 and continues their journey to Procedure-codes page")
      section5Journey1()
      //check procedure code when IsEIDR is Yes//
      And("User selects 1100 as procedure code and continues")
      ProcedureCodesPage.fillPage("1100")
      CommonPage.continue()
      And("User lands on Additional-Procedure-Codes page")
      AdditionalProcedureCodesPage.checkPage()
      And("User selects F44 as additional procedure code and continues")
      AdditionalProcedureCodesPage.fillPage("F44")
      CommonPage.continue()
      //check procedure code when IsEIDR is No//
      And("User navigates to Entry Into Declarant Records page")
      EntryIntoDeclarantRecordsPage.navigateToPage(EntryIntoDeclarantRecordsPage.path)
      And("User selects No to is this an entry into declarant records and continues")
      EntryIntoDeclarantRecordsPage.fillPage("No")
      CommonPage.continue()
      And("User navigates to Procedure codes page")
      ProcedureCodesPage.navigateToItemPage(ProcedureCodesPage.pageId)
      And("User selects 0015 as procedure code and continues")
      ProcedureCodesPage.fillPage("0015")
      CommonPage.continue()
      And("User lands on Additional-Procedure-Codes page")
      AdditionalProcedureCodesPage.checkPage()
      And("User selects 11A as additional procedure code and continues")
      AdditionalProcedureCodesPage.fillPage("11A")
      CommonPage.continue()
      And("User lands on Commodity-Details page")
      CommodityDetailsPage.checkPage()
      And("User enters commodity details code as 42034000 and description as Clothes and continues")
      CommodityDetailsPage.fillPage("42034000", "Clothes")
      CommonPage.continue()
      And("User lands on Package-Information page")
      PackageInformationPage.checkPage()
      And("User enters Cylinder as package type, with 5 packages and 67 as shipping mark for first package info and continues")
      PackageInformationPage.fillPage(genSequenceId("first"), "Cylinder", "5", "67")
      CommonPage.continue()
      And("User lands on Package-Information-List page")
      PackageInformationListPage.checkPage()
      And("User selects No on package information list page and continues")
      PackageInformationListPage.fillPage("No")
      CommonPage.continue()
      And("User lands on Commodity-Measure page")
      CommodityMeasurePage.checkPage()
      And("User enters gross weight as 5090 and net weight as 7010 and continues")
      CommodityMeasurePage.fillPage("5090", "7010")
      CommonPage.continue()
      And("User lands on Additional-Information-YesNo page")
      AdditionalInformationYesNoPage.checkPage()
      And("User selects Yes to add additional information")
      AdditionalInformationYesNoPage.fillPage("No")
      CommonPage.continue()
      And("User lands on Additional-Document page")
      AdditionalDocumentPage.checkPage()
      And("User enters C676 as code and GBAEOC70057 as identifier for first additional document and continues")
      AdditionalDocumentPage.fillPage(genSequenceId("first"), "C676", "identifier")
      CommonPage.continue()
      And("User lands on Additional-Document-List page")
      AdditionalDocumentListPage.checkPage()
      And("User selects No on additional document list page and continues")
      AdditionalDocumentListPage.fillPage("No")
      CommonPage.continue()
      Then("User should land on Declaration-Items-List page")
      DeclarationItemsListPage.checkPage()
      And("User selects No on declaration items list page and continues")
      DeclarationItemsListPage.fillPage("No")
      CommonPage.continue()
      Then("User should land on MiniCYA-Section-5 page")
      SummarySection5Page.checkPage()
      And("User checks the MiniCYA page for Section-5")
      SummarySection5Page.fillPage()
    }
  }

}
