package uk.gov.hmrc.test.ui.specs.Section5

import org.scalatest.{BeforeAndAfterAll, BeforeAndAfterEach, GivenWhenThen}
import org.scalatest.featurespec.AnyFeatureSpec
import org.scalatest.prop.TableDrivenPropertyChecks
import org.scalatest.verbs.ShouldVerb
import uk.gov.hmrc.selenium.webdriver.{Browser, ScreenshotOnFailure}
import uk.gov.hmrc.test.ui.pages.base.CommonPage
import uk.gov.hmrc.test.ui.pages.base.CommonPage.CommonStepPage.genSequenceId
import uk.gov.hmrc.test.ui.pages.base.CommonPage.{background, fillSection1ForDeclaration}
import uk.gov.hmrc.test.ui.pages.section5.*
import uk.gov.hmrc.test.ui.pages.section5.SummarySection5Page.section5Journey1
import uk.gov.hmrc.test.ui.specs.BaseSpec

class OccasionalJourneySpec
    extends AnyFeatureSpec with BaseSpec with GivenWhenThen with ShouldVerb with BeforeAndAfterAll
    with BeforeAndAfterEach with Browser with TableDrivenPropertyChecks with ScreenshotOnFailure {
  Feature("Section5 Occasional Journey") {
    Scenario("Perform a Low Value Occasional Arrived Declaration") {
      Given("the user clears data in cache")
      background()
      When("User fills Section1 for Occasional, arrived declaration")
      fillSection1ForDeclaration("Occasional", "arrived")
      And("User fills section2/3/4 and continues their journey to Procedure-codes page")
      section5Journey1()
      And("User selects 1040 as procedure code and continues")
      ProcedureCodesPage.fillPage("1040")
      CommonPage.continue()
      And("User lands on Additional-Procedure-Codes page")
      AdditionalProcedureCodesPage.checkPage()
      And("User selects 3LV as additional procedure code and continues")
      AdditionalProcedureCodesPage.fillPage("3LV")
      CommonPage.continue()
      Then("User lands on Commodity-Details page")
      CommodityDetailsPage.checkPage()
      And("User enters commodity details code as 84111100 and description as Aircraft engine and continues")
      CommodityDetailsPage.fillPage("84111100", "Aircraft engine")
      CommonPage.continue()
      And("User navigates to Dangerous Goods Code page")
      DangerousGoodsCodePage.navigateToItemPage(DangerousGoodsCodePage.pageId)
      And("User selects Yes to enter the code 1204 as dangerous goods and continues")
      DangerousGoodsCodePage.fillPage("Yes", "1204")
      CommonPage.continue()
      And("User lands on VAT-Rating page")
      VatRatingPage.checkPage()
      Then("User selects The goods are zero-rated option as goods being VAT zero-rated and continues")
      VatRatingPage.fillPage("The goods are zero-rated")
      CommonPage.continue()
      And("User lands on National-Additional-Code page")
      NationalAdditionalCodesPage.checkPage()
      And("User selects Yes and enters A103 as national additional code")
      NationalAdditionalCodesPage.fillPage("Yes", "A103")
      CommonPage.continue()
      And("User lands on National-Additional-Codes-List page")
      NationalAdditionalCodesListPage.checkPage()
      And("User selects No for adding another national code and continues")
      NationalAdditionalCodesListPage.fillPage("No")
      CommonPage.continue()
      And("User lands on Statistical-Value page")
      StatisticalValuePage.checkPage()
      And("User enters 1300 as statistical value and continues")
      StatisticalValuePage.fillPage("1300")
      CommonPage.continue()
      And("User lands on Package-Information page")
      PackageInformationPage.checkPage()
      And("User enters Basin as package type, with 100 packages and 104 as shipping mark for first package info and continues")
      PackageInformationPage.fillPage(genSequenceId("first"), "Basin", "100", "104")
      CommonPage.continue()
      And("User lands on Package-Information-List page")
      PackageInformationListPage.checkPage()
      And("User selects No on package information list page and continues")
      PackageInformationListPage.fillPage("No")
      CommonPage.continue()
      //Skipped Commodity Measurements and Supplementary Units//
      And("User lands on Additional-Information-YesNo page")
      AdditionalInformationYesNoPage.checkPage()
      And("User selects No to add additional information")
      AdditionalInformationYesNoPage.fillPage("No")
      CommonPage.continue()
      And("User lands on Licence-Required-YesNo page")
      LicenseRequiredYesNoPage.checkPage()
      And("User selects Yes to check if the goods require a licence and continues")
      LicenseRequiredYesNoPage.fillPage("Yes")
      CommonPage.continue()
      //skipped of documents required yes/no page//
      And("User lands on Additional-Document page")
      AdditionalDocumentPage.checkPage()
      And("User enters X002 as code and GBAEOC717572504502801 as identifier for first additional document")
      AdditionalDocumentPage.fillPage(genSequenceId("first"), "X002", "GBAEOC717572504502801")
      CommonPage.continue()
      And("User lands on Additional-Document-List page")
      AdditionalDocumentListPage.checkPage()
      And("User selects No on additional document list page and continues")
      AdditionalDocumentListPage.fillPage("No")
      And("User lands on Declaration-Items-List page")
      DeclarationItemsListPage.checkPage()
      And("User selects No on declaration items list page and continues")
      DeclarationItemsListPage.fillPage("No")
      CommonPage.continue()
      Then("User should land on MiniCYA-Section-5 page")
      SummarySection5Page.checkPage()
      And("User checks the MiniCYA page for Section-5")
      SummarySection5Page.fillPage()
    }
    
    Scenario(
      "Complete Items section on with Low Value Occasional Prelodged declaration and check change link functionality on Package Information, Additional Information and Additional Documents list pages"
    ) {
      Given("the user clears data in cache")
      background()
      When("User fills Section1 for OCCASIONAL, prelodged declaration")
      fillSection1ForDeclaration("OCCASIONAL", "prelodged")
      And("User fills section2/3/4 and continues their journey to Procedure-codes page")
      section5Journey1()
      And("User selects 1040 as procedure code and continues")
      ProcedureCodesPage.fillPage("1040")
      CommonPage.continue()
      And("User lands on Additional-Procedure-Codes page")
      AdditionalProcedureCodesPage.checkPage()
      And("User selects 000 as additional procedure code and continues")
      AdditionalProcedureCodesPage.fillPage("000")
      CommonPage.continue()
      CommodityDetailsPage.checkPage()
      And("User enters commodity details code as 28034005 and description as St Andrews golf ball whisky and continues")
      CommodityDetailsPage.fillPage("28034005", "St Andrews golf ball whisky")
      CommonPage.continue()
      //skipped fiscal information , additional-fiscal-references//
      And("User lands on Commodity-Details page")
      And("User navigates to Dangerous Goods Code page")
      DangerousGoodsCodePage.navigateToItemPage(DangerousGoodsCodePage.pageId)
      And("User selects Yes to enter the code 1204 as dangerous goods and continues")
      DangerousGoodsCodePage.fillPage("Yes", "1204")
      CommonPage.continue()
      And("User lands on Cus-Code page")
      CusCodePage.checkPage()
      And("User selects Yes to enter the code 12345678 as CUS code and continues")
      CusCodePage.fillPage("Yes", "12345678")
      CommonPage.continue()
      //skipped Vat Details//
      And("User lands on National-Additional-Code page")
      NationalAdditionalCodesPage.checkPage()
      And("User selects Yes and enters A103 as national additional code")
      NationalAdditionalCodesPage.fillPage("Yes", "A103")
      CommonPage.continue()
      And("User lands on National-Additional-Codes-List page")
      NationalAdditionalCodesListPage.checkPage()
      And("User selects No for adding another national code and continues")
      NationalAdditionalCodesListPage.fillPage("No")
      CommonPage.continue()
      //Skipping Statistical-Value when additional procedure code is not a low value declaration "3LV"//
      And("User lands on Package-Information page")
      PackageInformationPage.checkPage()
      And("User enters Aerosol as package type, with 10 packages and 1034 as shipping mark for first package info and continues")
      PackageInformationPage.fillPage(genSequenceId("first"), "Aerosol", "10", "1034")
      CommonPage.continue()
      And("User lands on Package-Information-List page")
      PackageInformationListPage.checkPage()
      And("User selects No on package information list page and continues")
      PackageInformationListPage.fillPage("No")
      CommonPage.continue()
      AdditionalInformationYesNoPage.checkPage()
      And("User selects Yes to add additional information and continues")
      AdditionalInformationYesNoPage.fillPage("Yes")
      CommonPage.continue()
      And("User lands on Additional-Information page")
      AdditionalInformationPage.checkPage()
      And("User enters 00400 as code and EXPORTER as required information as first additional information and continues")
      AdditionalInformationPage.fillPage(genSequenceId("first"), "00400", "EXPORTER")
      CommonPage.continue()
      And("User lands on Additional-Information-List page")
      AdditionalInformationListPage.checkPage()
      And("User selects No on additional information list page")
      AdditionalInformationListPage.fillPage("No")
      CommonPage.continue()
      And("User lands on Licence-Required-YesNo page")
      LicenseRequiredYesNoPage.checkPage()
      And("User selects Yes to check if the goods require a licence")
      LicenseRequiredYesNoPage.fillPage("Yes")
      CommonPage.continue()
      And("User lands on Additional-Document page")
      AdditionalDocumentPage.checkPage()
      And("User enters X002 as code and GBAEOC717572504502801 as identifier for first additional document and continues")
      AdditionalDocumentPage.fillPage(genSequenceId("first"), "X002", "GBAEOC717572504502801")
      CommonPage.continue()
      And("User lands on Additional-Document-List page")
      AdditionalDocumentListPage.checkPage()
      And("User selects No on additional document list page")
      AdditionalDocumentListPage.fillPage("No")
      CommonPage.continue()
      And("User lands on Declaration-Items-List page")
      DeclarationItemsListPage.checkPage()
      And("User selects No on declaration items list page and continues")
      DeclarationItemsListPage.fillPage("No")
      CommonPage.continue()
      Then("User should land on MiniCYA-Section-5 page")
      SummarySection5Page.checkPage()
      And("User checks the MiniCYA page for Section-5")
      SummarySection5Page.fillPage()
     //check Fiscal Reference page when Procedure code is 1042//
      When("User navigates to Procedure codes page")
      ProcedureCodesPage.navigateToItemPage(ProcedureCodesPage.pageId)
      And("User selects 1042 as procedure code and continue")
      ProcedureCodesPage.fillPage("1042")
      CommonPage.continue()
      And("User lands on Additional-Procedure-Codes page")
      AdditionalProcedureCodesPage.checkPage()
      And("User selects F75 as additional procedure code and continues")
      AdditionalProcedureCodesPage.fillPage("F75")
      CommonPage.continue()
      And("User lands on Fiscal-Information page")
      FiscalReferencesYesNoPage.checkPage()
      And("User selects Yes for Onward supply relief")
      FiscalReferencesYesNoPage.fillPage("Yes")
      CommonPage.continue()
      And("User lands on Additional-Fiscal-References page")
      FiscalReferencesPage.checkPage()
      And("User selects VAT registered country as Andorra : AD and VAT number as 1234 and continues")
      FiscalReferencesPage.fillPage("Andorra", "AD", "1234")
      CommonPage.continue()
      Then("User navigate to MiniCYA-Section-5 page")
      SummarySection5Page.navigateToPage(SummarySection5Page.path)
      And("User checks the MiniCYA page for Section-5")
      SummarySection5Page.fillPage()
     
    }
  }

}
